services:
  - type: web
    name: hackathon-portal-backend
    runtime: python
    pythonVersion: 3.11.4
    rootDir: backend
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
